# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# trigger:
#   branches:
#     include:
#     - main
#   paths:
#     include:
#     - version.txt

pool:
  name: demo-01-pool

variables:
- name: CLUSTER
  value: demo-01-ecs-cluster-dev 

stages:
- stage: PackageAndPublish
  jobs:
  - job: PackageAndPublish
    steps:
    - script: |
        echo Starging packaging
        export AWS_PAGER="cat"
      displayName: 'Base: Package succeeded'
    - script: |
        echo Hello world
        whoami
        docker images
        ls -l
        echo $CLUSTER
        terraform -help
        aws ecs list-tasks --cluster demo-01-ecs-cluster-dev
      displayName: 'Base: Publishing succeeded'

