# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# trigger:
#   branches:
#     include:
#     - main
#   paths:
#     include:
#     - version.txt

pool:
  name: demo-01-pool

variables:
- name: AWS_DEFAULT_REGION
  value: us-east-2
- name: AWS_ECR_URL
  value: 594914845356.dkr.ecr.us-east-2.amazonaws.com

stages:
- stage: PackageAndPublish
  jobs:
  - job: PackageAndPublish
    steps:
    - script: |
        echo Before-run
        export AWS_PAGER="cat" # set aws cli output command type to <cat> (by default <less>)
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ECR_URL
      displayName: 'Base: Before-run succeeded'
    - script: |
        echo Start packaging
        APP_TAG=$(cat version.txt)
        ECR_IMAGE="${AWS_ECR_URL}/${IMAGE_REPO_NAME}:${APP_TAG}"
        docker build . -t $ECR_IMAGE
        docker push $ECR_IMAGE        
      displayName: 'Base: Packaging succeeded'
    - script: |
        echo Start publishing
        docker push $ECR_IMAGE        
      displayName: 'Base: Publishing succeeded'

