# Pipeline to package and publish the app

trigger:
  branches:
    include:
    - main

pool:
  name: demo-01-pool

variables:
- name: AWS_DEFAULT_REGION
  value: us-east-2
- name: AWS_ECR_URL
  value: 594914845356.dkr.ecr.us-east-2.amazonaws.com
- name: IMAGE_REPO_NAME
  value: demo-01-ecr-dev

stages:
- stage: PackageAndPublish
  jobs:
  - job: PackageAndPublish
    steps:
    - script: |
        echo Before-run
        export AWS_PAGER="cat" # set aws cli output command type to <cat> (by default <less>)
        aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ECR_URL
      displayName: 'Base: Before-run'
    - script: |
        echo Start packaging and publishing
        APP_TAG=$(cat version.txt)
        ECR_IMAGE="${AWS_ECR_URL}/${IMAGE_REPO_NAME}:${APP_TAG}"
        docker build . -t $ECR_IMAGE    
        docker push $ECR_IMAGE  
      displayName: 'Base: Packaging and publishing'

